### ISSUE TITLE
Remaining tasks

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/boost-histogram#18]
These are the key elements to releasing the beta (an alpha might come sooner):

- [x] Add bin edges method
- [x] Add bin centers
- [x] Add accumulators
- [x] Add element type
- [x] Add `.view()` with flow option
- [x] Move to boost namespace (folder)
- [x] Add category int
- [x] Adapt the old test suite
- [x] Reduce the default number of dimensions to 12-16 (adjustable if built from source)
- [x] Add projections
- [x] Add histogram shortcut, with isinstance support
- [x] Support serialization (pickling as well as multiprocessing in Python < 3.8)
- [x] Add copy and deep copy support
- [x] Add comparison of axis with metadata
- [x] Use Boost 1.70 for dependencies
- [x] Add sum utilities (like Boost::Histogram, a user could just use numpy summing on a view, but at least a small shortcut like `.sum()` to help would be nice)
    - [x] Basic sum
    - [x]  `flow=False`
- [x] Add source dist support
- [x] Add C++14 manylinux wheel building to CI
- [x] add `__version__` and set it
- [x] make asarray return without flow
- [x] Rename `__call__` to `fill`
- [x] Combine fill functions (better keyword support)
- [x] Fix comparisons to avoid checking metadata internally
- [x] Add Python 2.7 + Windows support
- [x] Move common parts of setup functions to a header (making it easier to extend) (maybe add example)
- [x] Add shortcuts for axis types, fill out axis types (uflow, oflow, etc)
- [x] Restructure main .cpp a bit
- [x] Try to fix out of memory compile errors on 32-bit Linux by breaking up histogram.cpp a bit.
- [x] Add groups for the performance tests
- [x] Add some docs and read the docs support
- [x] Add rebin
- [x] Add shrink
- [x] Investigate requirements on 2.7 Windows
- [x] Convert to `template<class` instead of `template<typename`
- [x] Multithreading
    - [x] Add atomic backend
    - [x] Add threaded fill
    - [x] Add protections for resizing on atomic storage (could be done by Boost::Histogram first, see https://github.com/HDembinski/histogram/pull/6)
- [x] Add an underscore to the individual types for histograms and axes
- [x] Add an underscore to the `make_` functions for axes (and maybe histogram)
- [x] Allow view access into unlimited storage histograms
- [x] Work on project/shrink/etc
- [x] Remove single header file includes (`boost/histogram/histogram.hpp`)
- [x] Add weighted_profile histograms
- [x] Add profile histograms
- [x] Allow storages to drop the `()` when specified in `bh.histogram()`
- [x] Filling
    - [x] Allow setting samples
    - [x] Allow setting weights
    - [x] Add non-double fill
    - [x] Add higher performance vector fill? Might not be possible.
- [x] Work on `[]` access (#35)
    - [x] Add setting support
    - [ ] Add slice/shrink + project support
- [x] Add Numpy like functions (#91)
    - [x] Add `to_numpy`
    - [x] Add `from_numpy`
    - [x] Add histogram1d, etc... shortcuts (`= from_numpy(...).to_numpy()`)
- [x] Make axis objects iterable (yielding some kind of bin representation) (#89)
- [x] Release to PyPI (first "official" version, start CHANGELOG from this point)

**Comment by HDembinski** [comment]
`from_numpy` is only possible with a special storage, I think, if you do not want to copy the memory.

**Comment by HDembinski** [comment]
Is it necessary to have `from_numpy` and `to_numpy` in boost-histogram? Wouldn't this be convenience in hist?

**Comment by HDembinski** [comment]
Feel free to split off some issues and assign to me, I just assigned the adaptive operator support to myself.

**Comment by HDembinski** [comment]
You can also implement such a to-do list with issues tagged by milestones.

**Comment by henryiii** [comment]
> `from_numpy` is only possible with a special storage, I think, if you do not want to copy the memory.

I actually meant something else; what I was calling "from_numpy" would be three functions that took exactly the same arguments as `np.histogram()`, `np.histogram2d()`, and `np.histogramNd()`. This would allow boost-histogram to be a drop-in replacement for existing code bases. Probably means it was a bad name. What you are referring to would be useful too, though; it might be handled through hist and aghast though.

> Wouldn't this be convenience in hist?

If it's lightweight and doesn't add any dependencies, I think it might as well be in boost-histogram. Yes, though, it's more in the scope of hist.

**Comment by HDembinski** [comment]
> If it's lightweight and doesn't add any dependencies, I think it might as well be in boost-histogram. Yes, though, it's more in the scope of hist.

Good point!

**Comment by HDembinski** [comment]
> Yes, this was quicker for rapid development. As I clean up the low hanging fruit, several items may become issues. I'll probably split the filling off into an issue pretty soon.

Make sense, this is a good workflow.

**Comment by HDembinski** [comment]
regular_noflow and regular_uoflow should not be public classes. On the Python side, there should only be a `regular` class which has a private `_regular_noflow` or `_regular_uoflow` instance, similarly for the other axis types

**Comment by HDembinski** [comment]
`make_regular` should be hidden.

**Comment by HDembinski** [comment]
Likewise it should be done for the specialized histogram classes. There should be one `histogram` class and several private _histogram_* specializations. `make_histogram` should then be removed. There is no need to mirror it in Python. The only reason it exists in C++ is because we do not have deduction guides in C++14.

**Comment by HDembinski** [comment]
`threaded_fill` should just be `fill(... , threads=-1)`

**Comment by henryiii** [comment]
It already is, that changed a while ago... Though I think it's 0 for core-matching.

**Comment by henryiii** [comment]
I'll be moving all the names to private names soon. I'll move `make_histogram` as well; I am fine leaving that one public to mimic the C++ but I'm happy to hide it as well (and the Boost docs still say to use `make_histogram`, so I would consider it the main interface for histograms currently - and GCC 9 is the first C++17 complete GCC, and was released less than a week ago - Clang is not fully there yet).

**Comment by henryiii** [comment]
All remaining tasks are now available as separate issues. Will continue to check off here too for nostalgic reasons.

**Comment by henryiii** [comment]
Looks this this is done (one step moved to a later release).
